### ISSUE TITLE
site config relies on undocumented url mapper in webserver config

### ISSUE THREAD

**Issue by vorlonofportland** [msmunter/star.vote#41]
After creating an initial poll locally I am redirected to <http://localhost/3wxcx7mt/>.  This returns a 404 because there is no configuration to say that unknown urls should be handled by index.php.  Ideally the project would include reference config for how the apache webserver should be configured for processing of these non-static urls.

**Comment by msmunter** [comment]
The provided .htaccess file handles pretty-URL redirects, it needs Apache's AllowOverride directive set to "All" for the webroot. The README has been updated to include this instruction for most common Apache situations.
