### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by wolftune** [msmunter/star.vote#48]
See https://choosealicense.com/licenses/ for one reference.

The AGPL (first listed there) is my preference. It's strongest copyleft. That means while anyone can adapt the code and share it, any adaptation that is made available to others (not used just privately within an institution) must make available the source for their adaptations.

Any of the other licenses that are AGPL compatible are acceptable, but they would allow the software to be adapted to a proprietary context without releasing the source. In general, voting software should always be fully Open, so I don't want to encourage any proprietary voting software to exist. That said, there's *some* benefit to encouraging STAR use even in such proprietary contexts. But it's trivial enough to implement STAR, so they shouldn't need to use this code per se.

I think GitHub has a simple tool for adding a license. It's anyway as easy as adding LICENSE.md file with the contents of the LICENSE. It looks like all the code is currently just from @msmunter so there's no need to check with anyone else for copyright permission at this time.

The implication that is effective enough is that any pull-request or other submission will be under the same license unless someone specifies otherwise.

**Comment by msmunter** [comment]
This was discussed ages ago but never completed. AGPL is, indeed, preferred. License has been added and merged in PR #50.
